### ISSUE TITLE
Switch to fuzzy search

### ISSUE THREAD

**Issue by Ayushk4** [metakgp/Kronos#35]
As of now, the search is fully based on exact search, a partial search would be a more interactive and convenient one.

**Comment by thealphadollar** [comment]
@Ayushkaushal I'll be working on this.

**Comment by thealphadollar** [comment]
Do you really think we need fuzzy search in this app? It's not worth the time it would take to implement and it would rather ruin the application since mostly people will have what they want to seach in mind.

https://stackoverflow.com/questions/32337135/fuzzy-search-algorithm-approximate-string-matching-algorithm

**Comment by thealphadollar** [comment]
Yup, I can see the issue. I'll create an issue for it.
