### ISSUE TITLE
[BUG] Dropdown Not Functional On Safari

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/Kronos#45]
The dropdown that suggests probable matches is not functioning on Safari. 

![image](https://user-images.githubusercontent.com/32812320/49712988-ff9dcf80-fc6c-11e8-9481-01a69c014d76.png)

Here are some references that might help:
https://stackoverflow.com/questions/42392604/dropdown-menu-not-working-on-safari
https://forum.webflow.com/t/drop-down-menu-not-working-in-safari/39961

cc/ @artist007 If there is any more information, please provide.

**Comment by aditimaurya** [comment]
Hey, @thealphadollar can I try to fix this issue? The only thing we have to fix is the dropdown on Safari, right?

**Comment by thealphadollar** [comment]
Yes, that would be amazing. Thanks for the enthusiasm to contribute.

cc/ @Ayushk4

**Comment by Ayushk4** [comment]
PRs are welcome regarding this. @thealphadollar can you review and guide on this one?

**Comment by aditimaurya** [comment]
Hey, @Ayushk4  can you please assign this to me? I'm interested in resolving this issue.

**Comment by aditimaurya** [comment]
hey @Ayushk4, while I was running the Kronos in a MacBook, things which I've observed is that dropdown button is working but the icon is not visible. While someone is clicking on the text area dropdown menu is automatically visible. So, I think there is a problem with the visibility of the icon and not the functioning of the dropdown menu. 
Secondly, when we go down the dropdown list, navigator suddenly disappears after a point. I am figuring out the reasons as well, so if you have any idea why is this happening do let me know so that I can fix that. 
One more thing, I would like to say is that there's a problem in the cross-browser compatibility and not in codes ( what I have read and understood so far), so if I'm missing something do let me know. 

Thanks!

**Comment by aditimaurya** [comment]
Hi @Ayushk4, I think this issue is already resolved because currently when I checked the KRONOS with safari version 13.0.3 and 14.0  ( both in web and in mobile ) the drop-down is working well. I'll upload the screen recordings over slack ( here the file size is exceeding), please have a look at that. I guess, there was a problem with the older versions. 

cc/ @thealphadollar

**Comment by Ayushk4** [comment]
Thank you @aditimaurya . I am closing this issue now.

**Comment by Ayushk4** [comment]
Regarding your previous comment.

> hey @Ayushk4, while I was running the Kronos in a MacBook, things which I've observed is that dropdown button is working but the icon is not visible. While someone is clicking on the text area dropdown menu is automatically visible. So, I think there is a problem with the visibility of the icon and not the functioning of the dropdown menu.
Secondly, when we go down the dropdown list, navigator suddenly disappears after a point. I am figuring out the reasons as well, so if you have any idea why is this happening do let me know so that I can fix that.
One more thing, I would like to say is that there's a problem in the cross-browser compatibility and not in codes ( what I have read and understood so far), so if I'm missing something do let me know.

By MacBook, you mean safari browser?

> things which I've observed is that dropdown button is working but the icon is not visible. 
> Secondly, when we go down the dropdown list, navigator suddenly disappears after a point. I am figuring out the reasons as well, so if you have any idea why is this happening do let me know so that I can fix that.

I checked this in Safari 14.0.1 (MacBook). This still happens, though the dropdown functions well. I don't know why its behaving differently.

**Comment by aditimaurya** [comment]
> By MacBook, you mean safari browser?

Yeah! Safari browser, I mean.

> I checked this in Safari 14.0.1 (MacBook). This still happens, though the dropdown functions well. 

Is this regarding the visibility of the icon? Or the sudden disappearance of the navigator?

**Comment by Ayushk4** [comment]
> Is this regarding the visibility of the icon? Or the sudden disappearance of the navigator?
Both.
